### ISSUE TITLE
Container stops when terminal is resized

### ISSUE THREAD

**Issue by mnagy** [openshift/s2i-perl#82] opened 2016-05-06 09:08 UTC
Built S2I image exits when running from docker (not detached) and the terminal window is resized, apache quits on catching SIGWINCH signal.

```
$ docker run --rm -ti perl-sample-app
[...]
[ resize window ]
[Fri May 06 09:06:11.625146 2016] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
```

**Comment by mfojtik** [comment] 2016-05-06 09:19
not a bug: https://bugzilla.redhat.com/show_bug.cgi?id=1212224

**Comment by ppisar** [comment] 2016-05-06 11:52
The choice of the signal was really terrible. SIGUSR2 or any other by default
terminating signal would be more suitable.

I don't know how to fix it without injecting another process beetween docker
and httpd.

**Comment by bparees** [comment] 2016-06-10 05:21
closing as can't fix.

**Closed by bparees** 2016-06-10 05:21 UTC
